theme: jekyll-theme-minimal

exclude: ["README.md"]

# theme info
title: Martin Westgate
description: Research Fellow<br>Ecology & Evidence Synthesis<br>Fenner School of Environment & Society<br>Australian National University
logo: assets/img/MWestgate_image.jpg
