title: Martin Westgate
description: Research Fellow | ANU
logo: /assets/img/Westgate-Martin.jpeg
show_downloads: false
show_excerpts: false
google_analytics: UA-121833450-1
theme: jekyll-theme-minimal
exclude: ["README.md"]
collections_dir: collections
collections:
  publications:
    output: true
  software:
    output: true