project:
  type: website
website:
  title: "Martin Westgate"
  open-graph: true
  plausible-analytics: |
    <!-- Privacy-friendly analytics by Plausible -->
    <script async src="https://plausible.io/js/pa-QZEpD3zoHxPkIZnzqvonE.js"></script>
    <script>
      window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
      plausible.init()
    </script>
  navbar:
    title: false
    logo: "images/Westgate-Martin-small.jpeg"
    right:
      - text: Posts
        href: posts.qmd
      - text: Papers
        href: papers.qmd
      - text: Packages
        href: packages.qmd
      - text: Presentations
        href: presentations.qmd
      - icon: github
        href: https://github.com/mjwestgate
    search: true
format:
  html:
    theme: [litera, custom.scss]
    css: styles.css
    monofont: Fira Code
    highlight-style: arrow
    code-overflow: scroll
    linkcolor: "#2e6626"
    toc: true