---
author: <b>MJ Westgate</b>, DA Driscoll & DB Lindenmayer
title: "Can the intermediate disturbance hypothesis and information on species traits predict anuran responses to fire?"
subtitle: Oikos
date: 2012-01-23
volume: 121
pages: 1516-1524
doi: 10.1111/j.1600-0706.2011.19863.x
categories:
  - author-corresponding
  - topic-landscape-ecology
  - method-empirical
---

### Abstract
Fire is a common form of recurrent disturbance in many ecosystems, but ecological theory has a poor record of predicting animal responses to fire, at both species and assemblage levels. As a consequence, there is limited information to guide fire regime management for biodiversity conservation. We investigated a key research gap in the fire ecology literature; that is, the response of an anuran assemblage to variation in the fire return interval. We tested two hypotheses using a spatially-explicit fire database collected over a 40 year period: 1) species richness would peak at intermediate levels of disturbance. 2) Species with traits which enabled them to escape fire - burrowing or canopy dwelling - would be better able to survive fires, resulting in higher levels of occurrence in frequently burned sites. We found no evidence for either a reduction in species richness at locations with short fire return intervals, or a peak in species richness at intermediate levels of disturbance. Although we found some support for individual species responses to fire return intervals, these were inconsistent with the interpretation of burrowing or climbing being functional traits for fire-avoidance. Instead burrowing and climbing species may be more likely to be disadvantaged by frequent fire than surface dwelling frogs. More generally, our results show that many species in our study system have persisted despite a range of fire frequencies, and therefore that active management of fire regimes for anuran persistence may be unnecessary. The responses of anurans to fire in this location are unlikely to be predictable using simple life-history traits. Future work should focus on understanding the mechanistic underpinnings of fire responses, by integrating information on animal behavior and species' ecological requirements.