---
author: <b>MJ Westgate</b>, PS Barton, PW Lane & DB Lindenmayer
title: "Global meta-analysis reveals low consistency of biodiversity congruence relationships"
subtitle: Nature Communications
date: 2014-05-21
volume: 5
pages: 3899
doi: 10.1038/ncomms4899
categories:
  - author-corresponding
  - topic-surrogates-and-indicators
  - method-review
---

### Abstract
Knowledge of the number and distribution of species is fundamental to biodiversity conservation efforts, but this information is lacking for the majority of species on earth. Consequently, subsets of taxa are often used as proxies for biodiversity; but this assumes that different taxa display congruent distribution patterns. Here we use a global meta-analysis to show that studies of cross-taxon congruence rarely give consistent results. Instead, species richness congruence is highest at extreme spatial scales and close to the equator, while congruence in species composition is highest at large extents and grain sizes. Studies display highest variance in cross-taxon congruence when conducted in areas with dissimilar areal extents (for species richness) or latitudes (for species composition). These results undermine the assumption that a subset of taxa can be representative of biodiversity. Therefore, researchers whose goal is to prioritize locations or actions for conservation should use data from a range of taxa.