---
author: A Mortelliti, <b>MJ Westgate</b> & DB Lindenmayer
title: "Experimental evaluation shows limited influence of pine plantations on the connectivity of highly fragmented bird populations"
date: 2014-07-03
volume: 51
issue: 5
pages: 1179-1187
doi: 10.1111/1365-2664.12313
categories: 
  - author-contributing
  - topic-landscape-ecology
  - method-empirical
---

**Journal of Applied Ecology**

### Abstract
<ol>
  <li>Conversion of natural and agricultural areas to conifer plantations is an important element of global change. Despite their widespread distribution and global importance, it is still unclear whether conifer plantations hinder or enhance movement by biota.</li>

  <li>Population connectivity is difficult to quantify without detailed studies such as those using capture-mark-recapture methods. A novel solution is to quantify the synchrony in abundance between populations over time. Using this approach, more connected populations are expected to display synchrony, whereas disconnected populations are expected to fluctuate asynchronously. Here, we compared the relative effects of spatial proximity and matrix type on the population synchrony of a suite of forest-dependent birds in a long-term, fully controlled, and replicated landscape-scale experiment in south-eastern Australia.</li>

  <li>Our experiment consisted of comparing bird populations inhabiting remnant eucalypt patches surrounded by Radiata pine <i>Pinus radiata</i> plantations (50 patches) with bird populations inhabiting remnant eucalypt patches where the surrounding landscapes are grazing fields (55 patches). Our data set encompassed 10 years and included 52 bird species characterized by different life history traits. After controlling for the effects of rainfall and patch characteristics on population dynamics, we found that spatial proximity, not matrix type, was the main driver of population synchrony for 16 species. The effect of the pine plantation matrix was negative (it reduced synchrony). However, the magnitude of its effect was particularly low (being significant only in four species).</li>

  <li><em>Synthesis and applications</em>. Our results show that pine plantations do not increase connectivity. In fact, they have little effect, with the exception of a few species, for which they may constitute a barrier. The implications of our findings for landscape management are that the conversion of agricultural areas to plantation forestry does not promote substantial movement of individuals (to the extent that would synchronize populations). Therefore, plantation expansion should not be promoted on the belief that it increases connectivity relative to an agricultural matrix.</li>
</ol>