---
author: PW Lane, DB Lindenmayer, PS Barton, W Blanchard & <b>MJ Westgate</b>
title: "Visualisation of species pairwise associations: a case study of surrogacy in bird assemblages"
date: 2014-07-29
volume: 4
issue: 16
pages: 3279-3289
doi: 10.1002/ece3.1182
categories: 
  - author-contributing
  - topic-landscape-ecology
  - topic-surrogates-and-indicators
  - method-empirical
---

**Ecology and Evolution**

### Abstract
Quantifying and visualizing species associations are important to many areas of ecology and conservation biology. Species networks are one way to analyze species associations, with a growing number of applications such as food webs, nesting webs, plant-animal mutualisms, and interlinked extinctions. We present a new method for assessing and visualizing patterns of co-occurrence of species. The method depicts interactions and associations in an analogous way with existing network diagrams for studying pollination and trophic interactions, but adds the assessment of sign, strength, and direction of the associations. This provides a distinct advantage over existing methods of quantifying and visualizing co-occurrence. We demonstrate the utility of our new approach by showing differences in associations among woodland bird species found in different habitats and by illustrating the way these can be interpreted in terms of underlying ecological mechanisms. Our new method is computationally feasible for large assemblages and provides readily interpretable effects with standard errors. It has wide applications for quantifying species associations within ecological communities, examining questions about particular species that occur with others, and how their associations can determine the structure and composition of communities.