---
author: PS Barton, JC Pierson, <b>MJ Westgate</b>, PW Lane & DB Lindenmayer
title: "Learning from clinical medicine to improve the use of surrogates in ecology"
subtitle: Oikos
date: 2015-02-23
volume: 124
pages: 391-398
doi: 10.1111/oik.02007
categories: 
  - author-contributing
  - topic-surrogates-and-indicators
  - method-conceptual
---

### Abstract
Surrogates are used widely in ecology to detect or monitor changes in the environment that are too difficult or costly to assess directly. Yet most work on surrogates to date has been correlative, with little work on their predictive capacity or the circumstances under which they work. Our suggestion is to revisit and learn from research in the clinical medical sciences, including the causal statistical frameworks available to validate relationships between treatments, surrogate variables, and the outcome of interest. We adapt this medical thinking to ecology by providing a new framework that involves specification of the surrogate model, statistical validation, and subsequent evaluation in a range of spatial and temporal contexts. An inter-disciplinary surrogate concept will allow for a more rigorous approach to validating and evaluating proxy variables, thus advancing the selection and application of surrogates in ecology.