---
author: D Lindenmayer <em>et al.</em>
title: "A new framework for selecting environmental surrogates"
date: 2015-08-19
year: 2015
volume: 538
pages: 1029-1038
doi: 10.1016/j.scitotenv.2015.08.056
categories: 
  - author-contributing
  - topic-surrogates-and-indicators
  - method-conceptual
  - workshop-paper
---
D Lindenmayer, J Pierson, P Barton, M Beger, C Branquinho, A Calhoun, T Caro, H Greig, J Gross, J Heino, M Hunter, P Lane, C Longo, K Martin, WH McDowell, C Mellin, H Salo, A Tulloch & <b>M Westgate</b>

**Science of the Total Environment**

## Abstract
Surrogate concepts are used in all sub-disciplines of environmental science. However, controversy remains regarding the extent to which surrogates are useful for resolving environmental problems. Here, we argue that conflicts about the utility of surrogates (and the related concepts of indicators and proxies) often reflect context-specific differences in trade-offs between measurement accuracy and practical constraints. By examining different approaches for selecting and applying surrogates, we identify five trade-offs that correspond to key points of contention in the application of surrogates. We then present an 8-step Adaptive Surrogacy Framework that incorporates cross-disciplinary perspectives from a wide spectrum of the environmental sciences, aiming to unify surrogate concepts across disciplines and applications. Our synthesis of the science of surrogates is intended as a first step towards fully leveraging knowledge accumulated across disciplines, thus consolidating lessons learned so that they may be accessible to all those operating in different fields, yet facing similar hurdles.