---
author: DB Lindenmayer, SG Candy, SC Banks, <b>MJ Westgate</b>, K Ikin, JC Pierson, AIT Tulloch & PS Barton
title: "Do temporal changes in vegetation structure predict changes in bird occupancy additional to time since fire?"
subtitle: Ecological Applications
date: 2016-05-03
volume: 26
issue: 7
pages: 2267-2279
doi: 10.1002/eap.1367
categories: 
  - author-contributing
  - topic-landscape-ecology
  - method-empirical
---

### Abstract
Fire is a major ecological process in ecosystems globally. Its impacts on fauna can be both direct (e.g., mortality) and indirect (e.g., altered habitat), resulting in population recovery being driven by several possible mechanisms. Separating direct from indirect impacts of fire on faunal population recovery can be valuable in guiding management of biodiversity in fire-prone environments. However, resolving the influence of direct and indirect processes remains a key challenge because many processes affecting fauna can change concomitantly with time since fire. We explore the mechanisms influencing bird response to fire by posing the question, can temporal changes in vegetation structure predict changes in bird occurrence on sites, and can these be separated from other temporal changes using the surrogate of time since fire? We conducted a 12-yr study of bird and vegetation responses to fire at 124 sites across six vegetation classes in Booderee National Park, Australia. Approximately half of these sites, established in 2002, were burned by a large (>3000 ha) wildfire in 2003. To disentangle collinear effects of temporal changes in vegetation and direct demographic effects on population recovery that are subsumed by time since fire, we incorporated both longitudinal and cross-sectional vegetation effects in addition to time since fire within logistic structural equation models. We identified temporal changes in vegetation structure and richness of plant and bird species that characterized burned and unburned sites in all vegetation classes. For nine bird species, a significant component of the year trend was driven by temporal trends in one of three vegetation variables (number of understory or midstory plant species, or midstory cover). By contrast, we could not separate temporal effects between time since fire and vegetation attributes for bird species richness, reporting rate, and the occurrence of 11 other bird species. Our findings help identify species for which indirect effects of vegetation dominate recovery and thus may benefit from vegetation management where conservation actions are required and, conversely, those species for which direct effects of time since fire drive recovery, where simply leaving a system to recover following the last disturbance will be sufficient.