---
author: <b>MJ Westgate</b>, AIT Tulloch, PS Barton, JC Pierson & DB Lindenmayer
title: "Optimal taxonomic groups for biodiversity assessment: A meta-analytic approach"
date: 2016-03-10
volume: 40
pages: 539-548
doi: 10.1111/ecog.02318
categories: 
  - author-corresponding
  - topic-surrogates-and-indicators
  - method-empirical
  - method-review
---

**Ecography**

### Abstract
A fundamental decision in biodiversity assessment is the selection of one or more study taxa, a choice that is often made using qualitative criteria such as historical precedent, ease of detection, or available technical or taxonomic expertise. A more robust approach would involve selecting taxa based on the a priori expectation that they will provide the best possible information on unmeasured groups, but data to inform such hypotheses are often lacking. Using a global meta-analysis, we quantified the proportion of variability that each of 12 taxonomic groups (at the Order level or above) explained in the richness or composition of other taxa. We then applied optimization to matrices of pairwise congruency to identify the best set of complementary surrogate groups. We found that no single taxon was an optimal surrogate for both the richness and composition of unmeasured taxa if we used simple methods to aggregate congruence data between studies. In contrast, statistical methods that accounted for well-known drivers of cross-taxon congruence (spatial extent, grain size, and latitude) lead to the prioritization of similar surrogates for both species richness and composition. Advanced statistical methods were also more effective at describing known ecological relationships between taxa than simple methods, and show that congruence is typically highest between taxonomically and functionally dissimilar taxa. Birds and vascular plants were most frequently selected by our algorithm as surrogates for other taxonomic groups, but the extent to which any one taxon was the 'optimal' choice of surrogate for other biodiversity was highly context-dependent. In the absence of other information - such as in data-poor areas of the globe, and under limited budgets for monitoring or assessment - ecologists can use our results to assess which taxa are most likely to reflect the distribution of the richness or composition of 'total' biodiversity.