---
author: DB Lindenmayer, P Lane, <b>MJ Westgate</b>, BC Scheele, C Foster, C Sato, M Crane, D Michael, D Florance, K Ikin, PS Barton, LS O'Loughlin, N Robinson
title: "Tests of predictions associated with temporal changes in Australian bird populations"
date: 2018-04-19
volume: 222
pages: 212-221
doi: 10.1016/j.biocon.2018.04.007
categories: 
  - author-contributing
  - topic-landscape-ecology
  - method-empirical
---

**Biological Conservation**

### Abstract
Global biodiversity loss is the cumulative result of local species declines. To combat biodiversity loss, detailed information on the temporal trends of at-risk species at local scales is needed. Here we report the results of a 13-year study of temporal change in bird occupancy in one of the most heavily modified biomes worldwide; the temperate woodlands of south-eastern Australia. We sought to determine if temporal changes in bird species were different between three broad native vegetation types (old-growth woodland, regrowth woodland and restoration plantings) and between species traits (body size, migratory status, rarity, woodland dependency, or diet). We found evidence of decline for over a quarter of all bird species for which we had sufficient data for detailed analysis (30 out of 108 species). In contrast, only 14 species increased significantly. Temporal change of birds was linked to life-history attributes, with patterns often being habitat-dependent. Nectarivores and large-bodied birds declined across all vegetation types, whereas small-bodied species increased, particularly in restoration plantings. Contrasting with patterns documented elsewhere, resident but not migratory species declined, with this trend strongest in restoration plantings. Finally, our analyses showed that, as a group, common birds tended to decline whereas rare birds tended to increase, with effects for both most pronounced in restoration plantings. Our results highlight the benefit of targeted restoration planting for some species, but also demonstrate that many common species that have long-persisted in human-dominated landscapes are experiencing severe declines.