---
author: BS Scheele, S Legge, D Armstrong, P Copley, N Robinson, D Southwell, <b>MJ Westgate</b> & DB Lindenmayer
title: "How to improve threatened species management: An Australian perspective"
date: 2018-07-02
volume: 223
pages: 668-674
doi: 10.1016/j.jenvman.2018.06.084
categories: 
  - author-contributing
  - topic-landscape-ecology
  - method-conceptual
---

**Journal of Environmental Management**

### Abstract
Targeted threatened species management is a central component of efforts to prevent species extinction. Despite the development of a range of management frameworks to improve conservation outcomes over the past decade, threatened species management is still commonly characterised as ad hoc. Although there are notable successes, many management programs are ineffective, with relatively few species experiencing improvements in their conservation status. We identify underlying factors that commonly lead to ineffective and inefficient management. Drawing attention to some of the key challenges, and suggesting ways forward, may lead to improved management effectiveness and better conservation outcomes. We highlight six key areas where improvements are needed: 1) stakeholder engagement and communication; 2) fostering strong leadership and the development of achievable long-term goals; 3) knowledge of target species' biology and threats, particularly focusing on filling knowledge gaps that impede management, while noting that in many cases there will be a need for conservation management to proceed initially despite knowledge gaps; 4) setting objectives with measurable outcomes; 5) strategic monitoring to evaluate management effectiveness; and 6) greater accountability for species declines and failure to recover species to ensure timely action and guard against complacency. We demonstrate the importance of these six key areas by providing examples of innovative approaches leading to successful species management. We also discuss overarching factors outside the realm of management influence that can help or impede conservation success. Clear recognition of factors that make species' management more straightforward - or more challenging - is important for setting realistic management objectives, outlining strategic action, and prioritising resources. We also highlight the need to more clearly demonstrate the benefit of current investment, and communicate that the risk of under-investment is species extinctions. Together, improvements in conservation practice, along with increased resource allocation and re-evaluation of the prioritisation of competing interests that threaten species, will help enhance conservation outcomes for threatened species.