---
author: DB Lindenmayer, P Lane, CN Foster, <b>MJ Westgate</b>, BC Scheele, CF Sato, K Ikin, M Crane, D Michael & D Florance
title: "Do migratory and resident birds differ in their responses to interacting effects of climate, weather and vegetation?"
subtitle: Diversity & Distributions
date: 2018-12-11
volume: 25
issue: 3
pages: 449-461
categories: 
  - author-contributing
  - topic-landscape-ecology
  - method-empirical
---

DB Lindenmayer, P Lane, CN Foster, <b>MJ Westgate</b>, BC Scheele, CF Sato, K Ikin, M Crane, D Michael & D Florance

### Abstract
<h4>Aim</h4>
Knowledge of the individual and collective effects of habitat, weather variability and climate on bird populations is limited, with the result that species vulnerability to the collective impacts of global change is poorly understood. We quantified the effects of interactions between these potential drivers on the occurrence of resident, migratory and nomadic birds in Australian temperate woodlands.

<h4>Location</h4>
A 1.8 million hectare temperate woodland belt in south-eastern Australia.

<h4>Time period</h4>
2002-2015.

<h4>Major taxa studied</h4>
Temperate woodland birds.

<h4>Methods</h4>
We used logistic mixed models to quantify the factors affecting the occurrence of three groups of birds (residents, partial migrants and nomads) at 203 long-term field sites located in three vegetation types (restoration plantings, natural regrowth woodland and old growth woodland) surveyed repeatedly between 2002 and 2015. Potential explanatory variables included vegetation type, three long-term climate variables (mean annual rainfall, maximum temperature and minimum temperature), and the three corresponding weather variables for 12 months preceding each survey.

<h4>Results</h4>
We found four-way interactions between bird movement category, type of vegetation cover and rainfall (both as a long-term climate variable and as a short-term weather variable). Increased occurrence of nomads and partial migrants, but not resident species, was associated with high short-term rainfall. The effects were more marked in long-term climatically wet areas, and also differed between vegetation types. Models for maximum and minimum temperature were simpler than those for rainfall but showed evidence of partial migrants and nomadic species avoiding low minimum or high maximum temperatures in some vegetation types.

<h3>Main conclusions</h4>
Our analyses revealed that birds with different movement patterns exhibit different responses to weather and long-term climate. Nomadic species in particular respond to rainfall strongly in climatically wet locations (presumably because of large pulses in resources). Drying conditions resulting from climate change may therefore create problems for the future persistence of nomadic bird species.