---
author: CN Foster <em>et al.</em>
title: "How practitioners integrate decision triggers with existing metrics in conservation monitoring"
date: 2018-09-29
volume: 230
pages: 94-101
categories: 
  - author-contributing
  - topic-landscape-ecology
  - method-conceptual
  - workshop-paper
---
CN Foster, LS O'Loughlin, CF Sato, <b>MJ Westgate</b>, PS Barton, JC Pierson, JM Balmer, G Catt, J Chapman, T Detto, A Hawcroft, G Jones, RP Kavanagh, M McKay, D Marshall, KE Moseby, M Perry, D Robinson, JA Seddon, K Tuft & DB Lindenmayer

**Journal of Environmental Management**

### Abstract
Decision triggers are defined thresholds in the status of monitored variables that indicate when to undertake management, and avoid undesirable ecosystem change. Decision triggers are frequently recommended to conservation practitioners as a tool to facilitate evidence-based management practices, but there has been limited attention paid to how practitioners are integrating decision triggers into existing monitoring programs. We sought to understand whether conservation practitioners' use of decision triggers was influenced by the type of variables in their monitoring programs. We investigated this question using a practitioner-focused workshop involving a structured discussion and review of eight monitoring programs. Among our case studies, direct measures of biodiversity (e.g. native species) were more commonly monitored, but less likely to be linked to decision triggers (10% with triggers) than measures being used as surrogates (54% with triggers) for program objectives. This was because decision triggers were associated with management of threatening processes, which were often monitored as a surrogate for a biodiversity asset of interest. By contrast, direct measures of biodiversity were more commonly associated with informal decision processes that led to activities such as management reviews or external consultation. Workshop participants were in favor of including more formalized decision triggers in their programs, but were limited by incomplete ecological knowledge, lack of appropriately skilled staff, funding constraints, and/or uncertainty regarding intervention effectiveness. We recommend that practitioners consider including decision triggers for discussion activities (such as external consultation) in their programs as more than just early warning points for future interventions, particularly for direct measures. Decision triggers for discussions should be recognized as a critical feature of monitoring programs where information and operational limitations inhibit the use of decision triggers for interventions.