---
author: DB Lindenmayer, W Blanchard, D Blair, L McBurney, C Taylor, BC Scheele, <b>MJ Westgate</b>, N Robinson & CN Foster
title: "The response of arboreal marsupials to long-term changes in forest disturbance"
subtitle: Animal Conservation
date: 2020-09-03
doi: 10.1111/acv.12634
categories: 
  - author-contributing
  - topic-landscape-ecology
  - method-empirical
---

### Abstract
Quantifying the long-term population trajectory of species and the factors affecting these trends is a fundamental part of animal conservation. We describe the results of a long-term investigation of temporal changes in the occurrence of arboreal marsupials in the wet eucalypt forests of south-eastern Australia. The assemblage includes habitat specialists such as the vulnerable greater glider <i>Petauroides volans</i> and the critically endangered Leadbeater's possum <i>Gymnobelideus leadbeateri</i>, as well as common and widespread taxa. Using data gathered between 1997 and 2018, we quantified relationships between site occupancy of four marsupial species and spatio-temporal site and landscape-level variables, including the number of hollow-bearing trees at a site, and the extent of fire and logging in the surrounding landscape. We found evidence that: (1) The number of hollow-bearing trees (which are critical den sites for arboreal marsupials) has declined substantially in the past two decades. (2) There was a decline in all species of arboreal marsupials. (3) The presence of all species of arboreal marsupials was positively linked to the number of large old hollow-bearing trees at a site. (4) The extent of logging disturbance in the landscape surrounding a site had a positive impact on the sugar glider Petaurus breviceps but a negative effect on Leadbeater's possum. This suggests that ongoing logging will have further negative impacts on Leadbeater's possum. (5) The presence of the greater glider and sugar glider declined with increasing amounts of fire in the landscape. Negative fire effects are a concern as montane ash forests are increasingly susceptible to high-severity wildfires. Stronger efforts are needed to reduce the extent and frequency of logging and fire disturbance in mountain ash forests to protect arboreal marsupial populations.