---
author: A Jeliazkov et al.
title: "A global database for metacommunity ecology, integrating species, traits, environment and space"
date: 2020-01-08
volume: 7
pages: 6
doi: 10.1038/s41597-019-0344-7
categories: 
  - author-contributing
  - topic-biodiversity-informatics
  - method-empirical
---

Alienor Jeliazkov, Darko Mijatovic, Stéphane Chantepie, Nigel Andrew, Raphaël Arlettaz, Luc Barbaro, Nadia Barsoum, Alena Bartonova, Elena Belskaya, Núria Bonada, Anik Brind’Amour, Rodrigo Carvalho, Helena Castro, Damian Chmura, Philippe Choler, Karen Chong-Seng, Daniel Cleary, Anouk Cormont, William Cornwell, Ramiro de Campos, Nicole de Voogd, Sylvain Doledec, Joshua Drew, Frank Dziock, Anthony Eallonardo, Melanie J. Edgar, Fábio Farneda, Domingo Flores Hernandez, Cédric Frenette-Dussault, Guillaume Fried, Belinda Gallardo, Heloise Gibb, Thiago Gonçalves-Souza, Janet Higuti, Jean-Yves Humbert, Boris R. Krasnov, Eric Le Saux, Zoe Lindo, Adria Lopez-Baucells, Elizabeth Lowe, Bryndis Marteinsdottir, Koen Martens, Peter Meffert, Andres Mellado-Díaz, Myles H. M. Menz, Christoph F. J. Meyer, Julia Ramos Miranda, David Mouillot, Alessandro Ossola, Robin Pakeman, Sandrine Pavoine, Burak Pekin, Joan Pino, Arnaud Pocheville, Francesco Pomati, Peter Poschlod, Honor C. Prentice, Oliver Purschke, Valerie Raevel, Triin Reitalu, Willem Renema, Ignacio Ribera, Natalie Robinson, Bjorn Robroek, Ricardo Rocha, Sen-Her Shieh, Rebecca Spake, Monika Staniaszek-Kik, Michal Stanko, Francisco Leonardo Tejerina-Garro, Cajo ter Braak, Mark C. Urban, Roel van Klink, Sébastien Villéger, Ruut Wegman, <b>Martin J. Westgate</b>, Jonas Wolff, Jan Żarnowiec, Maxim Zolotarev & Jonathan M. Chase

**Scientific Data**

### Abstract
The use of functional information in the form of species traits plays an important role in explaining biodiversity patterns and responses to environmental changes. Although relationships between species composition, their traits, and the environment have been extensively studied on a case-by-case basis, results are variable, and it remains unclear how generalizable these relationships are across ecosystems, taxa and spatial scales. To address this gap, we collated 80 datasets from trait-based studies into a global database for metaCommunity Ecology: Species, Traits, Environment and Space; "CESTES". Each dataset includes four matrices: species community abundances or presences/absences across multiple sites, species trait information, environmental variables and spatial coordinates of the sampling sites. The CESTES database is a live database: it will be maintained and expanded in the future as new datasets become available. By its harmonized structure, and the diversity of ecosystem types, taxonomic groups, and spatial scales it covers, the CESTES database provides an important opportunity for synthetic trait-based research in community ecology.