---
author: <b>MJ Westgate</b>, C Crane, D Smith, C O'Malley, A Siegrist, D Florance, E Lang, M Crane, K Hingee, BC Scheele & DB Lindenmayer
title: "Improved management of farm dams increases vegetation cover, water quality, and macroinvertebrate biodiversity"
date: 2022-03-16
volume: 12
issue: 3
pages: e8636
doi: 10.1002/ece3.8636
categories: 
  - author-corresponding
  - topic-landscape-ecology
  - method-empirical
---

**Ecology and Evolution**

### Abstract
In many farming landscapes, aquatic features, such as wetlands, creeks, and dams, provide water for stock and irrigation, while also acting as habitat for a range of plants and animals. Indeed, some species threatened by land-use change may otherwise be considerably rarer—or even suffer extinction—in the absence of these habitats. Therefore, a critical issue for the maintenance of biodiversity in agricultural landscapes is the extent to which the management of aquatic systems can promote the integration of agricultural production and biodiversity conservation. We completed a cross-sectional study in southern New South Wales (southeastern Australia) to quantify the efficacy of two concurrently implemented management practices—partial revegetation and control of livestock grazing—aimed at enhancing the vegetation structure, biodiversity value, and water quality of farm dams. We found that excluding livestock for even short periods resulted in increased vegetation cover. Relative to unenhanced dams (such as those that remained unfenced), those that had been enhanced for several years were characterized by reduced levels of turbidity, nutrients, and fecal contamination. Enhanced dams also supported increased richness and abundance of macroinvertebrates. In contrast, unenhanced control dams tended to have high abundance of a few macroinvertebrate taxa. Notably, differences remained between the macroinvertebrate assemblages of enhanced dams and nearby “natural” waterbodies that we monitored as reference sites. While the biodiversity value of semilotic, natural waterbodies in the region cannot be replicated by artificial lentic systems, we consider the extensive system of farm dams in the region to represent a novel ecosystem that may nonetheless support some native macroinvertebrates. Our results show that management interventions such as fencing and grazing control can improve water quality in farm dams, improve vegetation structure around farm dams, and support greater abundance and diversity of aquatic macroinvertebrates.