---
author: M Littlefair, BC Scheele, <b>MJ Westgate</b> & DB Lindenmayer
title: "The ecological and biodiversity conservation values of farm dams: A systematic review"
date: 2024-05-13
doi: 10.1371/journal.pone.0303504
volume: 19
issue: 5
pages: e0303504
categories: 
  - author-contributing
  - topic-landscape-ecology
  - method-review
---

**PLOS ONE**

### Abstract
Biodiversity is in rapid decline globally with agriculture being one of the leading causes. Within agricultural landscapes, some features provide a benefit to biodiversity that is disproportionate to their spatial area. An interesting example is artificial ponds–or farm dams–which can support a large variety of taxa. Here, we present a global review of farm dam research related to biodiversity conservation objectives to provide an overview of the topics, key research insights, and the characteristics of current research. We used a three-stage process to screen literature and identified 104 relevant papers across 27 countries encompassing studies of 13 different taxa. Most of the studies were short-term (less than 5 years) with small sample sizes (less than 20 sites). Of the 104 papers, 88 were focussed primarily on ecological outcomes, such as species richness or abundance, and 15 on primary production outcomes, such as crop and livestock yield, despite addressing or measuring ecological metrics. Only one study measured both ecological and primary production outcomes. Studies frequently examined how the features of dams (79 studies) and attributes of the surrounding landscape (47 studies) impact particular species and communities. Terrestrial mammals (1 study) were under-represented in the literature with macrophytes (28 studies), macroinvertebrates (26 studies), and amphibians (19 studies) receiving the most attention. Our results reveal a growing trend towards recognizing farm dams as habitats for various taxa, including amphibians, beetles, dragonflies, and other macroinvertebrates within agricultural environments. Significant knowledge gaps exist in understanding how dam age, invasive species, and effective management practices impact the biodiversity conservation values of farm dams. Future research should emphasize enhancing biodiversity by collaborating with landholders to increase habitat through strategic vegetation planning, minimizing runoff and nutrient inflow, and restricting stock access.